export type UpgradeStat = 'fluxPerClick' | 'clickDecayPerSec' | 'fluxHarvestRate' | 'wattsPerFlux' | 'degsPerWatt' | 'thermalLimitDegs';

export interface StatValue {
	stat: UpgradeStat;
	value: number;
}

export const DefaultCoreStats: Record<UpgradeStat, number> = {
	fluxPerClick: 0.5,
	clickDecayPerSec: 0.25,
	fluxHarvestRate: 0,
	wattsPerFlux: 3.5,
	degsPerWatt: 0.2,
	thermalLimitDegs: 40
};

export const StatTypeToString: Record<UpgradeStat, string> = {
	fluxPerClick: 'flux/click',
	clickDecayPerSec: 'click decay/s',
	fluxHarvestRate: 'flux',
	wattsPerFlux: 'W/flux',
	degsPerWatt: '°C/W',
	thermalLimitDegs: 'Max °C'
} as const;

interface UpgradeEffect extends StatValue {
	method: 'add' | 'multiply';
}

export interface Upgrade {
	id: string;
	displayName: string;
	description: string;
	// Cost at first purchase
	cost: number;
	// Cost multiplier per level
	costScaling?: number;
	effects: UpgradeEffect[];
	// If true, considers negative effects to be good for the player
	invertPositivity?: boolean;
	// If true, visually displays the upgrade as one level higher than it actually is
	countOneHigher?: boolean;
}

export const Upgrades: Upgrade[] = [
	{
		id: 'manual-injector',
		displayName: 'Manual Injector',
		description:
			"Lacking automated mechanisms, Flux can be injected manually. It's neither efficient nor glamorous, but it might just get us off the ground.",
		cost: 6,
		effects: [
			{
				stat: 'fluxPerClick',
				method: 'add',
				value: 0.05
			}
		],
		countOneHigher: true
	},
	{
		id: 'injection-insulator',
		displayName: 'Injection Insulator',
		description: 'Improvements to insulation can help reduce the decay of Flux generated by Manual Injectors.',
		cost: 7.5,
		effects: [
			{
				stat: 'clickDecayPerSec',
				method: 'multiply',
				value: 0.97
			}
		],
		invertPositivity: true
	},
	{
		id: 'flux-injectors',
		displayName: 'Flux Injectors',
		description: 'Flux harvested passively from the surrounding area is automatically condensed and injected into Flux Cores.',
		cost: 85,
		effects: [
			{
				stat: 'fluxHarvestRate',
				method: 'add',
				value: 5
			}
		]
	},
	{
		id: 'concentration-lenses',
		displayName: 'Concentration Lenses',
		description: 'Specialised lenses focus Flux into a smaller area, making power generation more effective.',
		cost: 80,
		effects: [
			{
				stat: 'wattsPerFlux',
				method: 'multiply',
				value: 1.05
			}
		]
	},
	{
		id: 'thermal-recycling',
		displayName: 'Thermal Recycling',
		description:
			'Improvements to heat efficiency can reduce waste heat generated, increasing the amount of power that can be generated without overloading a Core.',
		cost: 145,
		effects: [
			{
				stat: 'degsPerWatt',
				method: 'multiply',
				value: 0.94
			}
		],
		invertPositivity: true
	},
	{
		id: 'thermal-coating',
		displayName: 'Thermal Coating',
		description: 'Advanced coatings can help dissipate heat, increasing the maximum safe operating temperature of a Core.',
		cost: 120,
		effects: [
			{
				stat: 'thermalLimitDegs',
				method: 'add',
				value: 4
			}
		]
	}
] as const;
