export type UpgradeStat = 'fluxPerClick' | 'clickDecayRate' | 'fluxHarvestRate' | 'wattsPerFlux' | 'heatPerWatt' | 'thermalLimitDeg';

export interface StatValue {
	stat: UpgradeStat;
	value: number;
}

export const DefaultCoreStats: Record<UpgradeStat, number> = {
	fluxPerClick: 1,
	clickDecayRate: 0.33,
	fluxHarvestRate: 0,
	wattsPerFlux: 0.1,
	heatPerWatt: 8,
	thermalLimitDeg: 40
};

export const StatTypeToString: Record<UpgradeStat, string> = {
	fluxPerClick: 'flux/click',
	clickDecayRate: 'click decay/s',
	fluxHarvestRate: 'flux/s',
	wattsPerFlux: 'W/flux',
	heatPerWatt: '°C/W',
	thermalLimitDeg: 'Max °C'
} as const;

interface UpgradeEffect extends StatValue {
	method: 'add' | 'multiply';
}

export interface Upgrade {
	id: string;
	displayName: string;
	description: string;
	// Cost at first purchase
	cost: number;
	// Cost multiplier per level
	costScaling?: number;
	effects: UpgradeEffect[];
	// If true, considers negative effects to be good for the player
	invertPositivity?: boolean;
}

export const Upgrades: Upgrade[] = [
	{
		id: 'manual-injector',
		displayName: 'Manual Injector',
		description:
			'Human-operated Flux injectors are neither the most efficient nor the most glamorous, but they can help jump-start a Core from nothing.',
		cost: 3,
		effects: [
			{
				stat: 'fluxPerClick',
				method: 'add',
				value: 0.05
			}
		]
	},
	{
		id: 'injection-insulator',
		displayName: 'Injection Insulator',
		description: 'Improvements to insulation can help reduce decay of Flux generated by Manual Injectors.',
		cost: 2,
		effects: [
			{
				stat: 'clickDecayRate',
				method: 'multiply',
				value: 0.97
			}
		],
		invertPositivity: true
	},
	{
		id: 'flux-injectors',
		displayName: 'Flux Injectors',
		description: 'Flux harvested passively from the surrounding area is automatically condensed and injected into Flux Cores.',
		cost: 8,
		effects: [
			{
				stat: 'fluxHarvestRate',
				method: 'add',
				value: 13.33
			}
		]
	},
	{
		id: 'thermal-recycling',
		displayName: 'Thermal Recycling',
		description:
			'Improvements to heat efficiency can reduce waste heat generated, increasing the amount of power that can be generated without overloading a Core.',
		cost: 10,
		effects: [
			{
				stat: 'heatPerWatt',
				method: 'multiply',
				value: 0.94
			}
		],
		invertPositivity: true
	},
	{
		id: 'thermal-coating',
		displayName: 'Thermal Coating',
		description: 'Advanced coatings can help dissipate heat, increasing the maximum safe operating temperature of a Core.',
		cost: 20,
		effects: [
			{
				stat: 'thermalLimitDeg',
				method: 'add',
				value: 4
			}
		]
	}
] as const;

export type UpgradeId = (typeof Upgrades)[number]['id'];
